import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-staffmanagement',
  imports: [RouterModule, CommonModule],
  templateUrl: './staffmanagement.component.html',
  styleUrl: './staffmanagement.component.css'
})
export class StaffmanagementComponent {


  groups = [
    {
      name: 'Nurses',
      email: 'nurses@hospital.com',
      region: 'Ward',
      subRegion: 'General',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/women/1.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/10.jpg',
        'https://randomuser.me/api/portraits/women/11.jpg',
        'https://randomuser.me/api/portraits/men/12.jpg',
      ],
    },
    {
      name: 'Surgeons',
      email: 'surgery@hospital.com',
      region: 'Operation Theater',
      subRegion: 'Surgical',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/2.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/13.jpg',
        'https://randomuser.me/api/portraits/women/14.jpg',
      ],
    },
    {
      name: 'Pathologists',
      email: 'pathology@hospital.com',
      region: 'Laboratory',
      subRegion: 'Diagnostics',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/3.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/15.jpg',
        'https://randomuser.me/api/portraits/men/16.jpg',
      ],
    },
    {
      name: 'Radiologists',
      email: 'radiology@hospital.com',
      region: 'Imaging',
      subRegion: 'X-Ray/CT',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/4.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/17.jpg',
        'https://randomuser.me/api/portraits/men/18.jpg',
      ],
    },
    {
      name: 'Anesthesiologists',
      email: 'anesthesia@hospital.com',
      region: 'Operation Theater',
      subRegion: 'Pre-Op',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/5.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/19.jpg',
        'https://randomuser.me/api/portraits/men/20.jpg',
      ],
    },
    {
      name: 'General Physicians',
      email: 'physicians@hospital.com',
      region: 'OPD',
      subRegion: 'General Medicine',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/6.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/21.jpg',
        'https://randomuser.me/api/portraits/men/22.jpg',
      ],
    },
    {
      name: 'Cardiologists',
      email: 'cardiology@hospital.com',
      region: 'Cardiac Unit',
      subRegion: 'Heart Center',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/women/7.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/23.jpg',
        'https://randomuser.me/api/portraits/women/24.jpg',
      ],
    },
    {
      name: 'Neurologists',
      email: 'neuro@hospital.com',
      region: 'Neuro Ward',
      subRegion: 'Neuro ICU',
      status: 'Inactive',
      image: 'https://randomuser.me/api/portraits/men/8.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/25.jpg',
        'https://randomuser.me/api/portraits/men/26.jpg',
      ],
    },
    {
      name: 'Orthopedics',
      email: 'ortho@hospital.com',
      region: 'Bone Center',
      subRegion: 'Ortho OPD',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/women/9.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/27.jpg',
        'https://randomuser.me/api/portraits/women/28.jpg',
      ],
    },
    {
      name: 'Pediatricians',
      email: 'pediatrics@hospital.com',
      region: 'Children Ward',
      subRegion: 'Pediatric ICU',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/10.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/29.jpg',
        'https://randomuser.me/api/portraits/men/30.jpg',
      ],
    },
    {
      name: 'Gynecologists',
      email: 'gynecology@hospital.com',
      region: 'Women Ward',
      subRegion: 'Maternity',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/women/11.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/31.jpg',
        'https://randomuser.me/api/portraits/women/32.jpg',
      ],
    },
    {
      name: 'Dermatologists',
      email: 'derma@hospital.com',
      region: 'Skin Clinic',
      subRegion: 'OPD',
      status: 'Inactive',
      image: 'https://randomuser.me/api/portraits/women/12.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/33.jpg',
        'https://randomuser.me/api/portraits/women/34.jpg',
      ],
    },
    {
      name: 'Oncologists',
      email: 'oncology@hospital.com',
      region: 'Cancer Center',
      subRegion: 'Chemotherapy',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/13.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/35.jpg',
        'https://randomuser.me/api/portraits/men/36.jpg',
      ],
    },
    {
      name: 'ENT Specialists',
      email: 'ent@hospital.com',
      region: 'ENT Ward',
      subRegion: 'Head/Neck',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/women/14.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/37.jpg',
        'https://randomuser.me/api/portraits/women/38.jpg',
      ],
    },
    {
      name: 'Ophthalmologists',
      email: 'eye@hospital.com',
      region: 'Eye Clinic',
      subRegion: 'Vision Testing',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/15.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/39.jpg',
        'https://randomuser.me/api/portraits/men/40.jpg',
      ],
    },
    {
      name: 'Psychiatrists',
      email: 'mentalhealth@hospital.com',
      region: 'Mental Health',
      subRegion: 'Therapy Ward',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/women/16.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/41.jpg',
        'https://randomuser.me/api/portraits/women/42.jpg',
      ],
    },
    {
      name: 'Pharmacists',
      email: 'pharmacy@hospital.com',
      region: 'Pharmacy',
      subRegion: 'Dispensary',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/17.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/43.jpg',
        'https://randomuser.me/api/portraits/men/44.jpg',
      ],
    },
    {
      name: 'Technicians',
      email: 'technicians@hospital.com',
      region: 'Equipment Room',
      subRegion: 'Diagnostics',
      status: 'Inactive',
      image: 'https://randomuser.me/api/portraits/men/18.jpg',
      members: [
        'https://randomuser.me/api/portraits/women/45.jpg',
        'https://randomuser.me/api/portraits/men/46.jpg',
      ],
    },
    {
      name: 'Receptionists',
      email: 'reception@hospital.com',
      region: 'Front Desk',
      subRegion: 'Main Entry',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/women/19.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/47.jpg',
        'https://randomuser.me/api/portraits/women/48.jpg',
      ],
    },
    {
      name: 'Housekeeping',
      email: 'cleaning@hospital.com',
      region: 'Facility',
      subRegion: 'All Floors',
      status: 'Active',
      image: 'https://randomuser.me/api/portraits/men/20.jpg',
      members: [
        'https://randomuser.me/api/portraits/men/49.jpg',
        'https://randomuser.me/api/portraits/women/50.jpg',
      ],
    },
  ];



  hospital = {
    name: 'PP Maniya Hospital',
    branches: [
      {
        name: 'PP Maniya Piplod',
        groups : [
          {
            name: 'Nurses',
            email: 'nurses@hospital.com',
            region: 'Ward',
            subRegion: 'General',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/1.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/10.jpg',
              'https://randomuser.me/api/portraits/women/11.jpg',
              'https://randomuser.me/api/portraits/men/12.jpg',
            ],
          },
          {
            name: 'Surgeons',
            email: 'surgery@hospital.com',
            region: 'Operation Theater',
            subRegion: 'Surgical',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/2.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/13.jpg',
              'https://randomuser.me/api/portraits/women/14.jpg',
            ],
          },
          {
            name: 'Pathologists',
            email: 'pathology@hospital.com',
            region: 'Laboratory',
            subRegion: 'Diagnostics',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/3.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/15.jpg',
              'https://randomuser.me/api/portraits/men/16.jpg',
            ],
          },
          {
            name: 'Radiologists',
            email: 'radiology@hospital.com',
            region: 'Imaging',
            subRegion: 'X-Ray/CT',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/4.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/17.jpg',
              'https://randomuser.me/api/portraits/men/18.jpg',
            ],
          },
          {
            name: 'Anesthesiologists',
            email: 'anesthesia@hospital.com',
            region: 'Operation Theater',
            subRegion: 'Pre-Op',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/5.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/19.jpg',
              'https://randomuser.me/api/portraits/men/20.jpg',
            ],
          },
          {
            name: 'General Physicians',
            email: 'physicians@hospital.com',
            region: 'OPD',
            subRegion: 'General Medicine',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/6.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/21.jpg',
              'https://randomuser.me/api/portraits/men/22.jpg',
            ],
          },
          {
            name: 'Cardiologists',
            email: 'cardiology@hospital.com',
            region: 'Cardiac Unit',
            subRegion: 'Heart Center',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/7.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/23.jpg',
              'https://randomuser.me/api/portraits/women/24.jpg',
            ],
          },
          {
            name: 'Neurologists',
            email: 'neuro@hospital.com',
            region: 'Neuro Ward',
            subRegion: 'Neuro ICU',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/men/8.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/25.jpg',
              'https://randomuser.me/api/portraits/men/26.jpg',
            ],
          },
          {
            name: 'Orthopedics',
            email: 'ortho@hospital.com',
            region: 'Bone Center',
            subRegion: 'Ortho OPD',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/9.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/27.jpg',
              'https://randomuser.me/api/portraits/women/28.jpg',
            ],
          },
          {
            name: 'Pediatricians',
            email: 'pediatrics@hospital.com',
            region: 'Children Ward',
            subRegion: 'Pediatric ICU',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/10.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/29.jpg',
              'https://randomuser.me/api/portraits/men/30.jpg',
            ],
          },
          {
            name: 'Gynecologists',
            email: 'gynecology@hospital.com',
            region: 'Women Ward',
            subRegion: 'Maternity',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/11.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/31.jpg',
              'https://randomuser.me/api/portraits/women/32.jpg',
            ],
          },
          {
            name: 'Dermatologists',
            email: 'derma@hospital.com',
            region: 'Skin Clinic',
            subRegion: 'OPD',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/women/12.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/33.jpg',
              'https://randomuser.me/api/portraits/women/34.jpg',
            ],
          },
          {
            name: 'Oncologists',
            email: 'oncology@hospital.com',
            region: 'Cancer Center',
            subRegion: 'Chemotherapy',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/13.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/35.jpg',
              'https://randomuser.me/api/portraits/men/36.jpg',
            ],
          },
          {
            name: 'ENT Specialists',
            email: 'ent@hospital.com',
            region: 'ENT Ward',
            subRegion: 'Head/Neck',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/14.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/37.jpg',
              'https://randomuser.me/api/portraits/women/38.jpg',
            ],
          },
          {
            name: 'Ophthalmologists',
            email: 'eye@hospital.com',
            region: 'Eye Clinic',
            subRegion: 'Vision Testing',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/15.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/39.jpg',
              'https://randomuser.me/api/portraits/men/40.jpg',
            ],
          },
          {
            name: 'Psychiatrists',
            email: 'mentalhealth@hospital.com',
            region: 'Mental Health',
            subRegion: 'Therapy Ward',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/16.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/41.jpg',
              'https://randomuser.me/api/portraits/women/42.jpg',
            ],
          },
          {
            name: 'Pharmacists',
            email: 'pharmacy@hospital.com',
            region: 'Pharmacy',
            subRegion: 'Dispensary',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/17.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/43.jpg',
              'https://randomuser.me/api/portraits/men/44.jpg',
            ],
          },
          {
            name: 'Technicians',
            email: 'technicians@hospital.com',
            region: 'Equipment Room',
            subRegion: 'Diagnostics',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/men/18.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/45.jpg',
              'https://randomuser.me/api/portraits/men/46.jpg',
            ],
          },
         
        ]
      },
      {
        name: 'PP Maniya Adajan',
        groups : [
          {
            name: 'Nurses',
            email: 'nurses@hospital.com',
            region: 'Ward',
            subRegion: 'General',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/1.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/10.jpg',
              'https://randomuser.me/api/portraits/women/11.jpg',
              'https://randomuser.me/api/portraits/men/12.jpg',
            ],
          },
          {
            name: 'Surgeons',
            email: 'surgery@hospital.com',
            region: 'Operation Theater',
            subRegion: 'Surgical',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/2.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/13.jpg',
              'https://randomuser.me/api/portraits/women/14.jpg',
            ],
          },
          {
            name: 'Pathologists',
            email: 'pathology@hospital.com',
            region: 'Laboratory',
            subRegion: 'Diagnostics',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/3.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/15.jpg',
              'https://randomuser.me/api/portraits/men/16.jpg',
            ],
          },
          {
            name: 'Radiologists',
            email: 'radiology@hospital.com',
            region: 'Imaging',
            subRegion: 'X-Ray/CT',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/4.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/17.jpg',
              'https://randomuser.me/api/portraits/men/18.jpg',
            ],
          },
          {
            name: 'Anesthesiologists',
            email: 'anesthesia@hospital.com',
            region: 'Operation Theater',
            subRegion: 'Pre-Op',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/5.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/19.jpg',
              'https://randomuser.me/api/portraits/men/20.jpg',
            ],
          },
          {
            name: 'General Physicians',
            email: 'physicians@hospital.com',
            region: 'OPD',
            subRegion: 'General Medicine',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/6.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/21.jpg',
              'https://randomuser.me/api/portraits/men/22.jpg',
            ],
          },
          {
            name: 'Cardiologists',
            email: 'cardiology@hospital.com',
            region: 'Cardiac Unit',
            subRegion: 'Heart Center',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/7.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/23.jpg',
              'https://randomuser.me/api/portraits/women/24.jpg',
            ],
          },
          {
            name: 'Neurologists',
            email: 'neuro@hospital.com',
            region: 'Neuro Ward',
            subRegion: 'Neuro ICU',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/men/8.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/25.jpg',
              'https://randomuser.me/api/portraits/men/26.jpg',
            ],
          },
          {
            name: 'Orthopedics',
            email: 'ortho@hospital.com',
            region: 'Bone Center',
            subRegion: 'Ortho OPD',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/9.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/27.jpg',
              'https://randomuser.me/api/portraits/women/28.jpg',
            ],
          },
          {
            name: 'Pediatricians',
            email: 'pediatrics@hospital.com',
            region: 'Children Ward',
            subRegion: 'Pediatric ICU',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/10.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/29.jpg',
              'https://randomuser.me/api/portraits/men/30.jpg',
            ],
          },
          {
            name: 'Gynecologists',
            email: 'gynecology@hospital.com',
            region: 'Women Ward',
            subRegion: 'Maternity',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/11.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/31.jpg',
              'https://randomuser.me/api/portraits/women/32.jpg',
            ],
          },
          {
            name: 'Dermatologists',
            email: 'derma@hospital.com',
            region: 'Skin Clinic',
            subRegion: 'OPD',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/women/12.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/33.jpg',
              'https://randomuser.me/api/portraits/women/34.jpg',
            ],
          },
          {
            name: 'Oncologists',
            email: 'oncology@hospital.com',
            region: 'Cancer Center',
            subRegion: 'Chemotherapy',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/13.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/35.jpg',
              'https://randomuser.me/api/portraits/men/36.jpg',
            ],
          },
          {
            name: 'ENT Specialists',
            email: 'ent@hospital.com',
            region: 'ENT Ward',
            subRegion: 'Head/Neck',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/14.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/37.jpg',
              'https://randomuser.me/api/portraits/women/38.jpg',
            ],
          },
          {
            name: 'Ophthalmologists',
            email: 'eye@hospital.com',
            region: 'Eye Clinic',
            subRegion: 'Vision Testing',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/15.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/39.jpg',
              'https://randomuser.me/api/portraits/men/40.jpg',
            ],
          },
          {
            name: 'Psychiatrists',
            email: 'mentalhealth@hospital.com',
            region: 'Mental Health',
            subRegion: 'Therapy Ward',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/16.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/41.jpg',
              'https://randomuser.me/api/portraits/women/42.jpg',
            ],
          },
          {
            name: 'Pharmacists',
            email: 'pharmacy@hospital.com',
            region: 'Pharmacy',
            subRegion: 'Dispensary',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/17.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/43.jpg',
              'https://randomuser.me/api/portraits/men/44.jpg',
            ],
          },
          {
            name: 'Technicians',
            email: 'technicians@hospital.com',
            region: 'Equipment Room',
            subRegion: 'Diagnostics',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/men/18.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/45.jpg',
              'https://randomuser.me/api/portraits/men/46.jpg',
            ],
          },
          {
            name: 'Receptionists',
            email: 'reception@hospital.com',
            region: 'Front Desk',
            subRegion: 'Main Entry',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/19.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/47.jpg',
              'https://randomuser.me/api/portraits/women/48.jpg',
            ],
          },
          {
            name: 'Housekeeping',
            email: 'cleaning@hospital.com',
            region: 'Facility',
            subRegion: 'All Floors',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/20.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/49.jpg',
              'https://randomuser.me/api/portraits/women/50.jpg',
            ],
          },
        ]
      },
      {
        name: 'PP Maniya Varacha',
        groups : [
          {
            name: 'Nurses',
            email: 'nurses@hospital.com',
            region: 'Ward',
            subRegion: 'General',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/1.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/10.jpg',
              'https://randomuser.me/api/portraits/women/11.jpg',
              'https://randomuser.me/api/portraits/men/12.jpg',
            ],
          },
          {
            name: 'Surgeons',
            email: 'surgery@hospital.com',
            region: 'Operation Theater',
            subRegion: 'Surgical',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/2.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/13.jpg',
              'https://randomuser.me/api/portraits/women/14.jpg',
            ],
          },
          {
            name: 'Pathologists',
            email: 'pathology@hospital.com',
            region: 'Laboratory',
            subRegion: 'Diagnostics',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/3.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/15.jpg',
              'https://randomuser.me/api/portraits/men/16.jpg',
            ],
          },
          {
            name: 'Radiologists',
            email: 'radiology@hospital.com',
            region: 'Imaging',
            subRegion: 'X-Ray/CT',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/4.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/17.jpg',
              'https://randomuser.me/api/portraits/men/18.jpg',
            ],
          },
          {
            name: 'Anesthesiologists',
            email: 'anesthesia@hospital.com',
            region: 'Operation Theater',
            subRegion: 'Pre-Op',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/5.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/19.jpg',
              'https://randomuser.me/api/portraits/men/20.jpg',
            ],
          },
          {
            name: 'General Physicians',
            email: 'physicians@hospital.com',
            region: 'OPD',
            subRegion: 'General Medicine',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/6.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/21.jpg',
              'https://randomuser.me/api/portraits/men/22.jpg',
            ],
          },
          {
            name: 'Cardiologists',
            email: 'cardiology@hospital.com',
            region: 'Cardiac Unit',
            subRegion: 'Heart Center',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/7.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/23.jpg',
              'https://randomuser.me/api/portraits/women/24.jpg',
            ],
          },
          {
            name: 'Neurologists',
            email: 'neuro@hospital.com',
            region: 'Neuro Ward',
            subRegion: 'Neuro ICU',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/men/8.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/25.jpg',
              'https://randomuser.me/api/portraits/men/26.jpg',
            ],
          },
          {
            name: 'Orthopedics',
            email: 'ortho@hospital.com',
            region: 'Bone Center',
            subRegion: 'Ortho OPD',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/9.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/27.jpg',
              'https://randomuser.me/api/portraits/women/28.jpg',
            ],
          },
          {
            name: 'Pediatricians',
            email: 'pediatrics@hospital.com',
            region: 'Children Ward',
            subRegion: 'Pediatric ICU',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/10.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/29.jpg',
              'https://randomuser.me/api/portraits/men/30.jpg',
            ],
          },
          {
            name: 'Gynecologists',
            email: 'gynecology@hospital.com',
            region: 'Women Ward',
            subRegion: 'Maternity',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/11.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/31.jpg',
              'https://randomuser.me/api/portraits/women/32.jpg',
            ],
          },
          {
            name: 'Dermatologists',
            email: 'derma@hospital.com',
            region: 'Skin Clinic',
            subRegion: 'OPD',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/women/12.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/33.jpg',
              'https://randomuser.me/api/portraits/women/34.jpg',
            ],
          },
          {
            name: 'Oncologists',
            email: 'oncology@hospital.com',
            region: 'Cancer Center',
            subRegion: 'Chemotherapy',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/13.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/35.jpg',
              'https://randomuser.me/api/portraits/men/36.jpg',
            ],
          },
          {
            name: 'ENT Specialists',
            email: 'ent@hospital.com',
            region: 'ENT Ward',
            subRegion: 'Head/Neck',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/14.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/37.jpg',
              'https://randomuser.me/api/portraits/women/38.jpg',
            ],
          },
          {
            name: 'Ophthalmologists',
            email: 'eye@hospital.com',
            region: 'Eye Clinic',
            subRegion: 'Vision Testing',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/15.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/39.jpg',
              'https://randomuser.me/api/portraits/men/40.jpg',
            ],
          },
          {
            name: 'Psychiatrists',
            email: 'mentalhealth@hospital.com',
            region: 'Mental Health',
            subRegion: 'Therapy Ward',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/16.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/41.jpg',
              'https://randomuser.me/api/portraits/women/42.jpg',
            ],
          },
          {
            name: 'Pharmacists',
            email: 'pharmacy@hospital.com',
            region: 'Pharmacy',
            subRegion: 'Dispensary',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/17.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/43.jpg',
              'https://randomuser.me/api/portraits/men/44.jpg',
            ],
          },
          {
            name: 'Technicians',
            email: 'technicians@hospital.com',
            region: 'Equipment Room',
            subRegion: 'Diagnostics',
            status: 'Inactive',
            image: 'https://randomuser.me/api/portraits/men/18.jpg',
            members: [
              'https://randomuser.me/api/portraits/women/45.jpg',
              'https://randomuser.me/api/portraits/men/46.jpg',
            ],
          },
          {
            name: 'Receptionists',
            email: 'reception@hospital.com',
            region: 'Front Desk',
            subRegion: 'Main Entry',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/women/19.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/47.jpg',
              'https://randomuser.me/api/portraits/women/48.jpg',
            ],
          },
          {
            name: 'Housekeeping',
            email: 'cleaning@hospital.com',
            region: 'Facility',
            subRegion: 'All Floors',
            status: 'Active',
            image: 'https://randomuser.me/api/portraits/men/20.jpg',
            members: [
              'https://randomuser.me/api/portraits/men/49.jpg',
              'https://randomuser.me/api/portraits/women/50.jpg',
            ],
          },
        ],
      }
    ]
  };
}
